### ISSUE TITLE
ARCHIVE REPO

### ISSUE THREAD

**Issue by midzdotdev** [acro5piano/kysely-migration-cli#28]
As you've said in your README at the end, the `kysely-ctl` project is very well documented and encapsulates all functionality offered by this repo.

I vouch for this to archived to remove any confusion.

**Comment by acro5piano** [comment]
I won't archive it for now. Because:

### 1/ Smaller bundle size

This could be a good reason to use this repo.

- kysely-migration-cli: 239KB
- kysely-ctl: 15.7MB

### 2/ API is different

`kysely-migration-cli` offers minimalistic API to align with each team's compilation flow.

### 3/ Still in use and usable

Even though kysely-ctl is more popular nowadays, decent people (including me) still uses it. Weekly downloads is around 1,800, which is not silly.

![image](https://github.com/user-attachments/assets/d665471c-329f-4d10-9eb4-43c71974299e)

In the future, I could archive this repo. But not now.

Feel free to reopen if you have further discussion.
